### ISSUE TITLE
Are we going to get a wind waker decomp

### ISSUE THREAD

**Issue by ItsFireninja** [zeldaret/tp#1898]
This isn't related, but are you ever going to make a wind waker decompilation, because I feel like that would be very interesting

**Comment by RevoSucks** [comment]
Discussion of such a project feels very out of scope for this repository.

**Comment by TakaRikka** [comment]
there's a wind waker decomp in the process of being made, but it's not ready for the public yet. please refer to the zeldaret discord for future updates regarding that, gonna close this
