### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by RevoSucks** [zeldaret/tp#386]
Maybe this is inappropriate to discuss yet, but currently oot https://github.com/Dragorn421/oot-licensing/issues/1 and mm https://github.com/louist103/mm-licensing/issues/1 are attempting to apply a license (such as CC0) to the repository by having every contributor (or past contributor) consent.

Are we doing anything similar?

**Comment by Pheenoh** [comment]
Yes, we should. I will open a separate issue to get consent from past contributors.
